Repository cse110-fa21-group27/cse110-fa21-group27, pull requests merged in 2021-12, with the labels that each got.

#186 Back end
  source/css/styles.css
  source/js/NavBar.js
  source/js/RecipeInfo.js
  source/js/SavedRecipePage.js
  source/js/main.js
  source/js/storage.js
Labels: Type: Enhancement, Priority: Extreme, Status: Review Needed

#188 Rudimentary css addition
  source/css/font.ttf
  source/css/fontRegular.ttf
  source/css/recipe_page.css
  source/css/search_page.css
  source/css/storageDemo.css
  source/css/styles.css
  source/js/Directions.js
  source/js/IngredientsInfo.js
  source/js/NavBar.js
  source/js/RecipeCard.js
  source/js/RecipeExpand.js
  source/js/RecipeInfo.js
  source/js/SavedRecipePage.js
Labels: Priority: Medium, Status: Review Needed, Type: Design, update

#194 Version 1 of SearchPage.js
  source/index.html
  source/js/NavBar.js
  source/js/SearchPage.js
  source/js/main.js
Labels: Type: Enhancement, Priority: Extreme, Status: Review Needed

#198 New theme changes with Css
  package-lock.json
  package.json
  source/css/font.ttf
  source/css/fontRegular.ttf
  source/css/recipe_page.css
  source/css/search_page.css
  source/css/styles.css
  source/font.ttf
  source/images/Spudly.png
  source/js/Directions.js
  source/js/IngredientsInfo.js
  source/js/NavBar.js
  source/js/RecipeCard.js
  source/js/RecipeInfo.js
  source/js/semiBold.ttf
Labels: Priority: Medium, Status: Review Needed, Type: Design, Design, update

#208 Rudimentary search functionality
  source/js/Directions.js
  source/js/NavBar.js
  source/js/Router.js
  source/js/SearchPage.js
  source/js/main.js
  source/js/storage.js
Labels: Type: Enhancement, Priority: High, Status: Review Needed

#217 cypress functionality for main
  cypress.json
  cypress/screenshots/spudly.js/Test the home page -- check that recipe 113's thumbnail isn't empty (failed).png
  cypress/screenshots/spudly.js/Test the home page -- check that recipe 12's thumbnail isn't empty (failed).png
  cypress/screenshots/spudly.js/Test the home page -- check that recipe 153's thumbnail isn't empty (failed).png
  cypress/screenshots/spudly.js/Test the home page -- check that recipe 162's thumbnail isn't empty (failed).png
  cypress/screenshots/spudly.js/Test the home page -- check that recipe 199's thumbnail isn't empty (failed).png
  cypress/screenshots/spudly.js/Test the home page -- check that recipe 95's thumbnail isn't empty (failed).png
  cypress/videos/directionstest.js.mp4
  cypress/videos/magictestNumbers.js.mp4
  cypress/videos/recipepagetest.js.mp4
  cypress/videos/savedrecipepagetest.js.mp4
  cypress/videos/spudly.js.mp4
Labels: Type: Enhancement, Priority: High, Status: Review Needed, Type: Testing

#233 Grocery list
  source/images/clear_black_24dp.svg
  source/index.html
  source/js/GroceryListPage.js
  source/js/IngredientsInfo.js
  source/js/NavBar.js
  source/js/RecipeInfo.js
  source/js/RecipePage.js
  source/js/main.js
  source/js/storage.js
Labels: Type: Enhancement, Priority: High, Status: Review Needed

#237 Grocery List feature
  source/images/clear_black_24dp.svg
  source/index.html
  source/js/GroceryListPage.js
  source/js/IngredientsInfo.js
  source/js/NavBar.js
  source/js/RecipeInfo.js
  source/js/RecipePage.js
  source/js/main.js
  source/js/storage.js
Labels: Type: Enhancement, Status: Available, Status: Review Needed

#239 Search filtering feature
  source/index.html
  source/js/SearchPage.js
  source/js/SearchPage_2.js
  source/js/main.js
  source/js/storage.js
Labels: Type: Enhancement, Priority: Extreme, Status: Review Needed

#234 Deleting old unnecessary files and removing unused functions.
  source/404.html
  source/js/GliderRecipe.js
  source/js/RecipeExpand.js
  source/js/main.js
Labels: Priority: Low, Type: Maintenance, Status: Review Needed
