Repository cse110-fa21-group27/cse110-fa21-group27, pull requests merged in 2021-11, with the labels that each got.

#50 add documentation to readme
  README.md
Labels: Status: Completed

#76 Made an ADR for organization of localStorage
  specs/adr/110821-localStorageStructure.md
  specs/adr/img/110821-localStorageStructure.png
Labels: Type: Documentation, Status: Completed

#93 Implementation of datastorage
  source/css/storageDemo.css
  source/html/storageDemo.html
  source/js/storage.js
Labels: Type: Enhancement, Status: Review Needed

#106 Demoing recipe json being put into glider
  source/index.html
  source/js/GliderRecipe.js
  source/js/RecipeCard.js
  source/js/main.js
  source/js/storage.js
  source/json/chicken_n_dumplings.json
  source/json/chicken_tortilla_soup.json
  source/json/gyudon.json
Labels: Type: Documentation, Type: Enhancement, Status: Review Needed

#139 NavBar is looking decent now
  source/js/NavBar.js
Labels: Type: Enhancement, Priority: Medium, Status: Review Needed

#153 eslint adr
  specs/adr/adr_eslint
Labels: Status: Review Needed

#154 directions component is completed.
  source/images/arrowUp.png
  source/images/checked.png
  source/images/unchecked.png
  source/js/Directions.js
Labels: Priority: Medium, Status: Review Needed

#161 to get the navBar appearance updated
  source/css/styles.css
  source/index.html
  source/js/main.js
Labels: update

#175 Spoonacular overhaul of backend
  .vscode/settings.json
  source/index.html
  source/js/Directions.js
  source/js/GliderRecipe.js
  source/js/IngredientsInfo.js
  source/js/NavBar.js
  source/js/RecipeCard.js
  source/js/RecipeInfo.js
  source/js/RecipePage.js
  source/js/Router.js
  source/js/SavedRecipePage.js
  source/js/main.js
  source/js/storage.js
  specs/adr/112721-APIchoice.md
  specs/adr/112721-frontendStructure.md
Labels: Type: Enhancement, Priority: Medium, Status: Review Needed
